language: python
python:
- '3.6'
install:
- pip install --upgrade -e . -r ./requirements/dev
script:
- export BOTO_CONFIG=/dev/null
- pytest --cov=checkQC tests/
after_success:
- codecov
notifications:
  email: false
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: OoaLWnPPvGh/CWunwV4tK4c7fz1Lzvte/GgKSWAxLYhLZmSIlic85i9RFsHurBOec7JPvz1UMiQLc4ZO9d4BwcO0hXDSVhPos7Xp+wZOYrYEmG9KCAnMoeR6WkurFzbumDLq+H3WiA02G1P/BmDV1Jr0nK512wEAPrBt+EgdbNrAW5n7BZ4dcWE2nHfHGa8yR1DOQHPMoRsg/WtCTwo8pYPNIpsFGoXlv0vcKzms2Tc83ZCI7sA09Qc/69X174KcPES77XDc4bIU3m0dwjB+Xea7MxNJNBAQlmzoG9yNcZBnXEOYrWd46NLJSwCx7Pbb1HcfrLzYukgGcGdnPMAFOKA0GsIzKRVHEplPfk7ybil8+9vzh1vPVXA120vStYoa2TkwflrbHLR7uV1TuO9zlLIuSyMzA89h81G5HOk/oHYQ6rAugHiAsRgXHYMD/eimktN4WAx4XjyrtSocS0m8MqWpKqiy8IKIL7OZFhHnlqQjcIgQMY/s7Nw7uytpiwxzaRz0SaaASM1aM9PfHgkF/dbLqwOLRyxhtwjWVVfoTXIRLJQv1Qn2EfsQPb+C9X3YrYEMI2p/66GPWznPhwj2MO4ECwT2029V4JfFHurJOAKMiqpTo/Q4rD+sURpryp8mZQn32bfkh3GqBsOpCg4FYeZqFxx3LHiOuu2Yt1Ws4TM=
  distributions: sdist bdist_wheel
  on:
    tags: true
