
hiseq2500_rapid:
  100-120:
    paired_end:
      handlers:
        - name: YieldHandler
          warning: 30 # Give lowest nbr in Gbp
          error: 20 # Give lowest nbr in Gbp
        - name: UndeterminedPercentageHandler
          warning: 0.01
          error: 0.02
  121-200:
    single_end:
      handlers:
        - name: YieldHandler
          warning: 300 # Give lowest nbr in Gbp
          error: 200 # Give lowest nbr in Gbp
        - name: UndeterminedPercentageHandler
          warning: 0.01
          error: 0.02
miseq:
  250-300:
    single_end:
      handlers:
        - name: YieldHandler
          warning: 300 # Give lowest nbr in Gbp
          error: 200 # Give lowest nbr in Gbp
        - name: UndeterminedPercentageHandler
          warning: 0.01
          error: 0.02
        - name: MyNewHandler
          min: 1
          max: 3
