
# First letter in instrument name is indicative of model
# i.e. SN7001335 is a HiSeq3500 since its name begins with
# SN
instrument_type_mappings:
  M: miseq
  D: hiseq2500
  ST: hiseqx
  A: novaseq

# Please note that intervals for read lengths are specified as: min < x <= max (i.e. upper inclusive, lower exclusive)
# All other intervals are exclusive.

default_handlers:
    - name: UndeterminedPercentageHandler
      warning: 10
      error: 30

hiseq2500_rapidhighoutput_v4:
  50-70:
    handlers:
      - name: ClusterPFHandler
        warning: 180 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 90 # 50 % of threshold for clusters pass filter
        error: unknown
  100-110:
    handlers:
      - name: ClusterPFHandler
        warning: 180 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 2
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 90 # 50 % of threshold for clusters pass filter
        error: unknown
  120-130:
    handlers:
      - name: ClusterPFHandler
        warning: 180 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 2
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 90 # 50 % of threshold for clusters pass filter
        error: unknown

hiseq2500_rapidrun_v2:
  50-70:
    handlers:
      - name: ClusterPFHandler
        warning: 110 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 55 # 50 % of threshold for clusters pass filter
        error: unknown
  100-125:
    handlers:
      - name: ClusterPFHandler
        warning: 110 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 2
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 55 # 50 % of threshold for clusters pass filter
        error: unknown
  150-175:
    handlers:
      - name: ClusterPFHandler
        warning: 110 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: unknown # Give percentage for reads greater than Q30
        error: 12.3 # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: unknown
        error: 80
      - name: ReadsPerSampleHandler
        warning: 55 # 50 % of threshold for clusters pass filter
        error: unknown
  250-265:
    handlers:
      - name: ClusterPFHandler
        warning: 110 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 55 # 50 % of threshold for clusters pass filter
        error: unknown

hiseqx_v2:
  150:
    handlers:
      - name: ClusterPFHandler
        warning: 400 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 200 # 50 % of threshold for clusters pass filter
        error: unknown

# TODO These are not the real novaseq qc criteria, but they need to be determined
#      once we know what they are. /JD 2017-10-05
novaseq_v1:
  150:
    handlers:
      - name: ClusterPFHandler
        warning: 400 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 200 # 50 % of threshold for clusters pass filter
        error: unknown

miseq_v2:
  25-50:
    handlers:
      - name: ClusterPFHandler
        warning: 10 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 1
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 5 # 50 % of threshold for clusters pass filter
        error: unknown
  150:
    handlers:
      - name: ClusterPFHandler
        warning: 10 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 2
        error: uknown
      - name: ReadsPerSampleHandler
        warning: 5 # 50 % of threshold for clusters pass filter
        error: unknown
  250:
    handlers:
      - name: ClusterPFHandler
        warning: 10 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 5 # 50 % of threshold for clusters pass filter
        error: unknown

miseq_v3:
  75:
    handlers:
      - name: ClusterPFHandler
        warning: 18 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 9 # 50 % of threshold for clusters pass filter
        error: unknown
  300:
    handlers:
      - name: ClusterPFHandler
        warning: 18 # Millons of clusters
        error: unknown
      - name: Q30Handler
        warning: 80 # Give percentage for reads greater than Q30
        error: unknown # Give percentage for reads greater than Q30
      - name: ErrorRateHandler
        warning: 5
        error: unknown
      - name: ReadsPerSampleHandler
        warning: 9 # 50 % of threshold for clusters pass filter
        error: unknown
