
# First letter in instrument name is indicative of model
# i.e. SN7001335 is a HiSeq3500 since its name begins with
# SN
instrument_type_mappings:
  M: miseq
  D: hiseq2500
  ST: hiseqx

# Please note that intervals for read lengths are specified as: min < x <= max (i.e. upper inclusive, lower exclusive)

default_handlers:
    - name: UndeterminedPercentageHandler
      warning: 10
      error: 30
#    - name: PoolingEvennessHandler
#      warning: 50
#      error: unknown # Each sample should have  >= x % of the clusters divded by the number of samples in the pool

hiseq2500_rapidhighoutput_v4:
  50-70:
    handlers:
      - name: ClusterPFHandler
        warning: 180
        error: unknown
      - name: Q30Handler
        warning: 7 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
  100-110:
    handlers:
      - name: ClusterPFHandler
        warning: 180
        error: unknown
      - name: Q30Handler
        warning: 14 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 2
        error: unknown
  120-130:
    handlers:
      - name: ClusterPFHandler
        warning: 180
        error: unknown
      - name: Q30Handler
        warning: 18 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 2
        error: unknown

hiseq2500_rapidrun_v2:
  50-70:
    handlers:
      - name: ClusterPFHandler
        warning: 110
        error: unknown
      - name: Q30Handler
        warning: 4.4 # Give lowest nbr in Gbp
        error: uknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
  100-125:
    handlers:
      - name: ClusterPFHandler
        warning: 110
        error: unknown
      - name: Q30Handler
        warning: 8.8 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 2
        error: unknown
  150-175:
    handlers:
      - name: ClusterPFHandler
        warning: 110
        error: unknown
      - name: Q30Handler
        warning: unknown # Give lowest nbr in Gbp
        error: 12.3 # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: unknown
        error: 3
  250-265:
    handlers:
      - name: ClusterPFHandler
        warning: 110
        error: unknown
      - name: Q30Handler
        warning: 20 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 5
        error: unknown

hiseqx_v2:
  150:
    handlers:
      - name: ClusterPFHandler
        warning: 400
        error: unknown
      - name: Q30Handler
        warning: 39 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 5
        error: unknown

miseq_v2:
  25-50:
    handlers:
      - name: ClusterPFHandler
        warning: 10
        error: unknown
      - name: Q30Handler
        warning: 0.2 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 1
        error: unknown
  150:
    handlers:
      - name: ClusterPFHandler
        warning: 10
        error: unknown
      - name: Q30Handler
        warning: 1.1 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 2
        error: uknown
  250:
    handlers:
      - name: ClusterPFHandler
        warning: 10
        error: unknown
      - name: Q30Handler
        warning: 1.8 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 5
        error: unknown

miseq_v3:
  75:
    handlers:
      - name: ClusterPFHandler
        warning: 18
        error: unknown
      - name: Q30Handler
        warning: 1.1 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 1.5
        error: unknown
  300:
    handlers:
      - name: ClusterPFHandler
        warning: 18
        error: unknown
      - name: Q30Handler
        warning: 3.7 # Give lowest nbr in Gbp
        error: unknown # Give lowest nbr in Gbp
      - name: ErrorRateHandler
        warning: 5
        error: unknown
